import { Fragment } from "react";
import RegisterDemand from "../../src/components/desktop/RegisterDemand";
import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";


const Index = () => {
    return (
        <Fragment>
            <Head>
                <title>جدید</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon/favicon.ico" />
            </Head>
            <RegisterDemand />
        </Fragment>
    );
}


export const getServerSideProps = wrapper.getServerSideProps(
    async (context) => {
      return {
        props: {
          ...(await serverSideTranslations(context.locale, ["basic"])),
          // Will be passed to the page component as props
        },
      };
    }
  );

export default Index;