import { Box, Container, useMediaQuery, useTheme } from "@mui/material";
import Head from "next/head";
import { Fragment } from "react";
import Footer from "../Home/Footer";
import Desktop from "./desktop";
import Mobile from "./mobile";
import Signin from "../Home/Header/SignIn";
import Navbar_Win from "../Home/Header/Navbar/Navbar_Win";
import NavBar_Mob from "./mobile/NavBar_Mob";

const RegisterDemand = () => {

    const theme = useTheme();
    const fullScreen = useMediaQuery(theme.breakpoints.down("md"));


    return (
        <Fragment>
            <Head>
                <title>جدید</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Box display={{ xs: "block", md: "none" }} id="navbar-mobile">
                <Container maxWidth="psm">
                    <NavBar_Mob />
                </Container>
            </Box>

            <Box display={{ xs: "none", md: "block" }}>
                <Signin />
                <Container maxWidth="xl">
                    <Navbar_Win />
                </Container>
            </Box>
            <Box>
                {fullScreen ? <Mobile /> : <Desktop />}
            </Box>
            <Footer/>
        </Fragment>
    )
}

export default RegisterDemand;