import { Fragment } from "react";
import {
  addDataRequest,
  handleLoadingSkeleton,
} from "../../../src/components/redux/showdemand";
import { wrapper } from "../../../src/components/redux/store/configureStore";
import http from "../../../src/components/utils/ConfigDefaults";
import Head from "next/head";
import ShowDemand from "../../../src/components/ShowDemand";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const Code = ({ title }) => {
  return (
    <Fragment>
      <Head>
        <title>{`متقاضی ${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ShowDemand />
    </Fragment>
  );
};

export const getServerSideProps = wrapper.getServerSideProps(
  async (context) => {
    const getCode = context.params.code;
    context.store.dispatch(handleLoadingSkeleton(true));
    // const res = (
    //   await http.get(
    //     `https://moteghazi.com/api/1.0.0/requirement/requirement?code=${getCode}`
    //   )
    // ).data.requirement;
    const res = (await http.get(`/code`)).data.requirement;
    context.store.dispatch(addDataRequest(res));
    context.store.dispatch(handleLoadingSkeleton(false));
    return {
      props: {
        title: res.title,
        ...(await serverSideTranslations(context.locale, ["basic"])),
        // Will be passed to the page component as props
      },
    };
  }
);

export default Code;
