import { Fragment, useEffect } from "react";
import { addDataRequest } from "../../../src/components/redux/showdemand";
import { wrapper } from "../../../src/components/redux/store/configureStore";
import http from "../../../src/components/utils/ConfigDefaults";
import Head from "next/head";
import ShowDemand from "../../../src/components/desktop/ShowDemand";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const Code = ({ title, getCode }) => {
  useEffect(() => {
    if (typeof window !== "undefined" && getCode) {
      const array = JSON.parse(localStorage.getItem("historyCard"));
      if (array) {
        const find = array.find((e) => e.code == getCode);
        if (!find) {
          localStorage.setItem(
            "historyCard",
            JSON.stringify([...array, { code: getCode }])
          );
        }
      } else {
        localStorage.setItem(
          "historyCard",
          JSON.stringify([{ code: getCode }])
        );
      }
    }
  }, []);

  return (
    <Fragment>
      <Head>
        <title>{`متقاضی ${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon/favicon.ico" />
      </Head>
      <ShowDemand />
    </Fragment>
  );
};

export const getServerSideProps = wrapper.getServerSideProps(
  async (context) => {
    console.log(context.params);
    const getCode = context.params.code;
    const title = await http
      // .get(
      //   `https://moteghazi.com/api/1.0.0/requirement/requirement?code=${getCode}`
      // )
      .get(`/code`)
      .then(async (res) => {
        await context.store.dispatch(addDataRequest(res.data.requirement));
        const title = res.data.requirement.title;
        return title;
      })
      .catch((err) => console.log(err));
    return {
      props: {
        title: title ?? "سامانه متقاضی",
        getCode,
        ...(await serverSideTranslations(context.locale, ["basic"])),
        // Will be passed to the page component as props
      },
    };
  }
);

export default Code;
