import Head from "next/head";
import { Fragment } from "react";
import Content from "../content";
import Footer from "../Footer";
import Header from "../Header";

const Layout = () => {
  return (
    <Fragment>
      <Head>
        <title>سامانه متقاضی</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon/favicon.ico" />
      </Head>
      <Header />
      <Content />
      <Footer />
    </Fragment>
  );
};

export default Layout;
